make erlang-mk: Copy build.config after switching to $(ERLANG_MK_COMMIT)
If the local build.config has changes compared to upstream's
master branch, and $(ERLANG_MK_COMMIT) also brings changes to this
file, copying the local file to the checkout before switching to
$(ERLANG_MK_COMMIT) caused git-checkout(1) to abort with:

    error: Your local changes to the following files would be overwritten by checkout:
    	build.config
    Please, commit your changes or stash them before you can switch branches.
    Aborting

While here, fix `core-upgrade-custom-repo` test case: without switching
back the alternate erlang.mk repository to its master branch, the clone
always got the test-copyright branch by default, making the
ERLANG_MK_COMMIT check ineffective.